import { describe, it, expect } from "vitest";
import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { glyphLabel, glyphPath, glyphRefs, glyphs } from "../../src/lib/glyphs";

// The manifest is GENERATED by tools/bake_glyphs.py (every build). We assert the
// contract the readers + generator depend on - never brittle counts: it is a v2
// manifest, every ref resolves to a real file with a label, and slugs are one token.
const here = fileURLToPath(new URL(".", import.meta.url));
const assetsDir = resolve(here, "../../public/assets/glyphs");

describe("glyph registry (v2, generated)", () => {
  it("is a v2 manifest carrying a generatedAt provenance stamp", () => {
    expect(glyphs.schemaVersion).toBe(2);
    expect(glyphs.generatedAt).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/);
  });

  it("resolves every ref to an existing file and a non-empty label", () => {
    for (const ref of glyphRefs()) {
      const file = glyphPath(ref).replace("/assets/glyphs/", "");
      expect(existsSync(resolve(assetsDir, file)), file).toBe(true);
      expect(glyphLabel(ref).length, ref).toBeGreaterThan(0);
    }
  });

  it("keys every glyph by a one-token [a-z0-9]+ slug", () => {
    for (const pack of Object.keys(glyphs.packs)) {
      for (const slug of Object.keys(glyphs.packs[pack])) {
        expect(slug, `${pack}.${slug}`).toMatch(/^[a-z0-9]+$/);
      }
    }
  });
});

describe("resolver", () => {
  it("round-trips a ref to a base-aware POSIX path", () => {
    expect(glyphPath("shapes.circle")).toBe("/assets/glyphs/shapes/circle.svg");
  });

  it("throws on an unknown ref", () => {
    expect(() => glyphPath("nope.zzz")).toThrow(/unknown glyph/);
  });
});
